### ISSUE TITLE
Working demo app

### ISSUE THREAD

**Issue by DePasqualeOrg** [mzbac/flux.swift#2]
I had some trouble getting the code in the readme to work, so I created this simple demo app: https://github.com/DePasqualeOrg/Flux-Demo

**Comment by mzbac** [comment]
the readme only have very basic usage of it. you could have a look at the https://github.com/mzbac/flux.swift.cli/blob/main/Sources/cli.swift see more details. Let me know if still having troubles

**Comment by DePasqualeOrg** [comment]
I'm not having trouble. I made a demo app that works, which I linked to in my comment. But the code in the readme does not work.

**Comment by mzbac** [comment]
Sorry for the misunderstanding, thanks for making the demo app.  I will double update the readme with more details example.
